### ISSUE TITLE
Changing the reader mode affects the results

### ISSUE THREAD

**Issue by tomrossi7** [maxmind/GeoIP2-ruby#28]
I'm using `maxmind-geoip2 (0.5.0)` and seeing something strange when I use the mode `MaxMind::DB::MODE_MEMORY`

This works as expected:
```
      reader = MaxMind::GeoIP2::Reader.new('GeoLite2-City.mmdb')
      record = reader.city('128.101.101.101')
      record.country.name  # United States
```

This returns nil:
```
      reader = MaxMind::GeoIP2::Reader.new('GeoLite2-City.mmdb', mode: MaxMind::DB::MODE_MEMORY)
      record = reader.city('128.101.101.101')
      record.country.name  # nil
```

**Comment by horgh** [comment]
Try creating the reader this way:

```ruby
MaxMind::GeoIP2::Reader.new('GeoLite2-City.mmdb', ['en'], mode: MaxMind::DB::MODE_MEMORY)
```

It looks like right now the options hash is getting used as the locale code. When we try to use that as the locale to find the default name, none matches, leading to `nil`.

Perhaps we can improve the parameter validation here!

**Comment by tomrossi7** [comment]
Thanks @horgh! 

A hash of options may be better:
`MaxMind::GeoIP2::Reader.new('GeoLite2-City.mmdb', locales: ['en'], mode: MaxMind::DB::MODE_MEMORY)`
