### ISSUE TITLE
OpenSSL::SSL::SSLError

### ISSUE THREAD

**Issue by wengzilla** [maxmind/GeoIP2-ruby#50]
I occasionally receive the following error. It seems to happen fairly sporadically (~1 per 100K requests). Does anyone have suggestions around a fix here? Is there a way to move from SSL to TLS and would that help? 

`OpenSSL::SSL::SSLError
SSL_connect returned=1 errno=0 peeraddr=[2606:4700::6810:252f]:443 state=error: sslv3 alert handshake failure`

My server is currently using the following runtime: `ruby ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) +jemalloc [x86_64-linux]`

**Comment by horgh** [comment]
Can you print this constant `OpenSSL::OPENSSL_VERSION`? I'm not sure an OpenSSL version would be the cause if it's generally working though. I would suspect a network issue.

Re: SSL to TLS - it is likely using TLS already, despite the output.

It might be worth adding a retry to your code.

Another thing you could try is setting `OpenSSL.debug = true`, e.g. before you run any of this code:

```ruby
require 'openssl'
OpenSSL.debug
[your code]
```

I don't know what all that shows, but I noticed it's an option!

**Comment by wengzilla** [comment]
Thanks for the fast response! So when I type in the version, I get this `OpenSSL 1.1.1n  15 Mar 2022"`. Seems like it's up to date-ish.

When you say network issue, do you think that would be on the MaxMind API side?

Re: Adding the retry. Can definitely try to catch and retry but I'd love to figure out whether or not there's an easier fix.

**Comment by horgh** [comment]
I haven't heard of others having similar issues. It's hard to say what would be going on. You could try contacting support@maxmind.com and they might be able to help look into it further.

**Comment by wengzilla** [comment]
Thank you!
